version: "3.2"
services:
  hairlog-react:
    restart: always
    command : npm start
    container_name: hairlog-front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true